
name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  static-analysis:
    name: "Static Analysis"
    uses: "doctrine/.github/.github/workflows/static-analysis.yml@1.4.1"
    with:
      composer-root-version: "2.3"
      php-version: "8.1"
